#!/usr/bin/env python3
"""
gen_build_timestamp.py — generate build_timestamp.c

Writes a C source file that exposes `build_timestamp[]` as a string whose
value is `__TIMESTAMP__` — the compiler's own file-modification time for
that translation unit.  Because this file is rewritten on every build, the
compiler always sees the actual build time rather than the last time
clocks.c (or any other steady-state file) was edited.

Usage:
    python3 gen_build_timestamp.py <output_path>

The output file should be inside a directory that is already part of the
board's build (e.g. Board/build_timestamp.c or src/build_timestamp.c).

Each board's build system is responsible for calling this script as a
pre-build step.  See the board-specific CLAUDE.md or .cproject/Makefile
for how the pre-build step is wired up.
"""
import sys
from pathlib import Path

if len(sys.argv) != 2:
    sys.stderr.write("usage: gen_build_timestamp.py <output_path>\n")
    sys.exit(1)

out = Path(sys.argv[1])
out.parent.mkdir(parents=True, exist_ok=True)

content = (
    "/* generated by TimbreOS/gen_build_timestamp.py — do not edit */\n"
    "const char build_timestamp[] = __TIMESTAMP__;\n"
)

out.write_text(content)
print("[gen_build_timestamp] wrote %s" % out)
