// PID declarations  generated by parsepids.py  Dec 05, 2016  18:44:56

#ifndef PID_H
#define PID_H

#define ACK_BIT 0x80 	// used for indicating SPS frames
#define SPS_BIT 0x40 	// used for indicating type of an SPS frame
#define PID_BITS (0xFF&(~(ACK_BIT|SPS_BIT))) 	// used to mask off upper bits
#define CONFIG 0x00 	// for exchanging configurations on a link: spid + specifics; ie testframe
#define SPS_ACK 0x1 	// confirm sps; link only - not networkable
#define WHO_PIDS (SPS_ACK) 	// all pids greater than, use the who header for routing
#define SPS 0x2 	// used for initializing SPS frame acks and setting id
#define PING 0x3 	// to check other end
#define PING_BACK 0x4 	// expected response to a PING
#define GET_VERSION 0x5 	// get the version number
#define VERSION_NO 0x6 	// return the version number
#define TALK_IN 0x7 	// keyboard input to be interpreted
#define TALK_OUT 0x8 	// used to send emits out usb port
#define EVAL 0x9 	// evaluate text with destination; who, text
#define CALL_CODE 0xa 	// call code starting at this location; who, addr32
#define MEMORY 0xb 	// use for memory transactions: read/write/erase/confirm...
#define FILES 0xc 	// user for file transactions: read/write/delete/...
#define MAX_PIDS 0xd 	// number of PIDS defined
#define MAX_FRAME_LENGTH (254) 	// no more than 254; set according to link resources
#define MAX_FRAMES (5) 	// number of frames floating around system
#define SPS_RETRIES (5) 	// maximum number of SPS retries
#define SFP_POLL_TIME (2) 	// polling in link down
#define SFP_SPS_TIME (2500) 	// time between retransmissions
#define SFP_FRAME_TIME (50) 	// maximum time to wait between bytes for a frame
#define SFP_FRAME_PROCESS (1000) 	// maximum time to wait for frame processing
#define STALE_RX_FRAME (1000) 	// number of milliseconds to hang onto a received frame

#define FOR_EACH_PID(P) \
	P(EVAL) /* 0x9 */ \
	P(TALK_OUT) /* 0x8 */ \
	P(PING) /* 0x3 */ \
	P(SPS) /* 0x2 */ \
	P(SPS_ACK) /* 0x1 */ \
	P(CONFIG) /* 0x00 */ \
	P(VERSION_NO) /* 0x6 */ \
	P(GET_VERSION) /* 0x5 */ \
	P(PING_BACK) /* 0x4 */ \
	P(SPS_BIT) /* 0x40 */ \
	P(TALK_IN) /* 0x7 */ \
	P(ACK_BIT) /* 0x80 */ \
	P(FILES) /* 0xc */ \
	P(MEMORY) /* 0xb */ \
	P(CALL_CODE) /* 0xa */ \
	P(MAX_PIDS) /* 0xd */ \

#endif