// CPU ID declarations  generated by parsecpuids.py  Oct 23, 2016  01:41:07

// don't modify this file. Make changes to cpuids.txt and regenerate
#define HOST 0x0 	// 
#define ME 0x0 	// 
#define YOU 0x0 	// 
#define DIRECT 0x0 	// 
#define MAIN_CPU 0x1 	// 
#define MAIN_HOST 0x2 	// host ports on cpus
#define USB_HOST 0x3 	// USB SFP port
#define ROUTING_POINTS 0x4 	// number of points for routing
unsigned char whoami(void);