// System dictionaries  generated by parsewords.py  Mar 01, 2017  16:58:05

// names are kept in flash; arrays are used; reduces space requirements
#include "cli.h"

#define NAMES(name) PROGMEM char name[] = {
#define NAME(s) s "\000"
#define END_NAMES ""}; // empty string to cover empty array

#define BODIES(functions) vector functions[] = {
#define BODY(f) (void * const)f,
#define CONSTANTBODY(f)  (void * const)CII,(void * const)&f,
#define CONSTANTNUMBER(n) (void * const)CII,(void * const)n,
#define END_BODIES };

void CII(void);

// Names and function binding for words, constants and immediates
// Names and function binding for words, constants and immediates

// Words
NAMES(wordnames)
	NAME("help")		//  print words with one line help; allow wild card filtering
	NAME("words")		//  list all words in dictionary
	NAME("hi")		//  test funciton
	NAME("tx")		//  ( c ) send a character out LEUART 1 port
END_NAMES

void help(void);
void words(void);
void hello(void);
void sendLe1(void);

BODIES(wordbodies)
	BODY(help)
	BODY(words)
	BODY(hello)
	BODY(sendLe1)
END_BODIES

// Immediates
NAMES(immediatenames)
END_NAMES


BODIES(immediatebodies)
END_BODIES

// Constants
NAMES(constantnames)
END_NAMES


BODIES(constantbodies)
END_BODIES

